### ISSUE TITLE
Fix issue with TutByJobSearchUtilTest

### ISSUE THREAD

**Issue by andrei-punko** [andrei-punko/java-interview#1]
```
search(by.andd3dfx.sitesparsing.tutby.TutByJobSearchUtilTest)  Time elapsed: 3.095 sec  <<< FAILURE!
java.lang.AssertionError: Next url should be present
Expected: is "http://jobs.tut.by/search/vacancy?L_is_autosearch=false&area=1002&clusters=true&enable_snippets=true&text=java&page=1"
     but: was "http://jobs.tut.by/search/vacancy?area=1002&text=java&page=1"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at by.andd3dfx.sitesparsing.tutby.TutByJobSearchUtilTest.search(TutByJobSearchUtilTest.java:25)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by andrei-punko** [comment]
Moved to https://github.com/andrei-punko/java-crawlers/issues/1
